var exercises = {
  strength: {
    'squats': 'http://multigymmtl.com/wp-content/uploads/2015/08/squats.jpg',
    'lunge': 'http://www.kingofthegym.com/wp-content/uploads/2012/11/benefits-of-lunges-woman-barbell-lunge.jpg',
    'leg curl': 'https://fthmb.tqn.com/kX_WDyxCzgpYTAOBbgcocNdvyrg=/735x0/about/leg-curl-56ca64385f9b5879cc4cfa23.jpg',
    'leg extension': 'https://www.bodybuilding.com/exercises/exerciseImages/sequences/53/Male/l/53_2.jpg',
    'leg press': 'https://www.bodybuilding.com/exercises/exerciseImages/sequences/215/Male/l/215_2.jpg',
    'toe raises': 'http://www.leehayward.com/exercises/calves/seated_calf1.jpg',
    'pullup': 'http://cpi.studiod.com/www_livestrong_com/photos.demandstudios.com/getty/article/108/132/492198470_XS.jpg',
    'barbell curl': 'https://www.bodybuilding.com/exercises/exerciseImages/sequences/210/Male/m/210_2.jpg',
    'dumbbell curl': 'https://i.ytimg.com/vi/8d2we4UqOSs/maxresdefault.jpg',
    'tricep extension': 'https://www.bodybuilding.com/exercises/exerciseImages/sequences/345/Female/l/345_1.jpg',
    'pulldown': 'https://www.bodybuilding.com/exercises/exerciseImages/sequences/143/Female/m/143_2.jpg',
    'dip': 'https://jfkbodyweightworkouts.files.wordpress.com/2012/09/bench-dips.jpg',
    'seated row': 'https://i2.wp.com/www.bodybuildingestore.com/wp-content/uploads/2016/02/Seated-Row-Exercises.jpg',
    'single-arm dumbbell row': 'https://www.bodybuilding.com/images/2016/june/10-best-muscle-building-back-exercises-v2-7-700xh.jpg',
    'close-grip pulldown': 'https://www.bodybuilding.com/images/2016/june/10-best-muscle-building-back-exercises-v2-6-700xh.jpg',
    'wide grip pullup': 'https://www.bodybuilding.com/images/2016/june/10-best-muscle-building-back-exercises-v2-3-700xh.jpg',
    'barbell deadlift': 'https://www.bodybuilding.com/images/2016/june/10-best-muscle-building-back-exercises-v2-1-700xh.jpg',
    'bent-over barbell deadlift': 'https://www.bodybuilding.com/images/2016/june/10-best-muscle-building-back-exercises-v2-2-700xh.jpg',
    'shoulder press': 'https://www.bodybuilding.com/exercises/exerciseImages/sequences/74/Female/m/74_2.jpg',
    'overhead press': 'http://www.kingofthegym.com/wp-content/uploads/2012/11/overhead-press-benefits.jpg',
    'band lateral raise': 'https://www.trainonline.com/images/exercises/female_exercise-band-standing-lateral-raises_2.jpg',
    'shoulder shrug': 'https://www.bodybuilding.com/exercises/exerciseImages/sequences/96/Female/l/96_1.jpg',
    'dumbbell dront raise': 'http://worldonline.media.clients.ellingtoncms.com/img/photos/2010/10/11/G0_3_moves004_t640.JPG?a6ea3ebd4438a44b86d2e9c39ecf7613005fe067',
    'dumbbell lateral raise': 'https://www.oxygenmag.com/.image/t_share/MTQ1MzQ3MzE1NDIzODQ4MjA5/dumbbell-lateral-raise.jpg',
    'chest press': 'https://www.bodybuilding.com/exercises/exerciseImages/sequences/889/Female/l/889_2.jpg',
    'pushup': 'https://images.askmen.com/1080x540/sports/bodybuilding/askmen-push-up-challenge-1106349-TwoByOne.jpg',
    'bench press': 'https://www.t-nation.com/system/publishing/articles/10003817/original/The-Sad-Truth-Anout-the-Bench-Press.jpg?1470075815',
    'incline press': 'https://www.bodybuilding.com/exercises/exerciseImages/sequences/3311/Male/l/3311_2.jpg',
    'pec deck': 'https://s-media-cache-ak0.pinimg.com/originals/69/8e/f6/698ef66504e418ce95a5c070f77c6bae.jpg',
    'chest flies': 'https://www.bodybuilding.com/exercises/exerciseImages/sequences/214/Female/m/214_1.jpg',
    'sit ups': 'https://www.bodybuilding.com/exercises/exerciseImages/sequences/202/Female/m/202_2.jpg',
    'bicycles': 'https://lovelifelupus.files.wordpress.com/2012/05/bicycles-exercise.jpg',
    'plank': 'https://i.ytimg.com/vi/pSHjTRCQxIw/maxresdefault.jpg',
    'leg raises': 'https://www.t-nation.com/system/publishing/article_assets/4610/original/Leg-Raise.jpg?ts=1490647384',
    'crunches': 'http://img.aws.livestrongcdn.com/ls-article-image-673/cpi.studiod.com/www_livestrong_com/photos.demandstudios.com/getty/article/144/210/493541956_XS.jpg',
    'flutter kick': 'https://www.bodybuilding.com/exercises/exerciseImages/sequences/267/Male/l/267_1.jpg'
  },
  cardio: {
    'run': 'http://dreamatico.com/data_images/run/run-6.jpg',
    'bike': 'https://604now.com/wp-content/uploads/2014/05/biketour-300x194.png',
    'swim': 'http://content.active.com/Assets/Active.com+Content+Site+Digital+Assets/Triathlon/580x370/4+Swim+Workouts/Swim+4.jpg',
    'row': 'http://allsportspk.com/wp-content/uploads/2016/09/rowing.jpg',
    'stairs': 'http://triathlonmagazine.ca/wp-content/uploads/2016/02/ThinkstockPhotos-517998297.jpg',
    'walk': 'http://s.eatthis-cdn.com/media/images/ext/216268148/morning-walk-longer-life-in-20-minutes.jpg',
  }
}

export default exercises;
